export const examples = [
  //undefined,
  //'',
  //{},
  //{S:'FF'},
  //'S=FFFFF+F',
  //'=experimentColor,S=F,F=F+SF-fSF,_a=150,_j=.04,_k=1,_l=1,_n=2,_z=2,_cb=#0077,_cd=#f077,_cc=#fff7',
  //'=ex1b,S=F,F=F+SF-fSF,_a=150,_j=.04,_k=1,_l=1.2,_n=2,_z=2,_cb=#000,_cd=#ffffff74,_cc=#fff0',
  //'=ex2,S=F+F+f+F,_j=0.1,_k=1,_l=1,_n=1,_o=.4,_cb=#0000,_cd=#f007,_cc=#00f7',
  //'=WARNINGblurDemo,S=U+V+W+V+R,R=V+R+U+V+W+V+R-W,U=V+R+U+V+W+V+R-U+V+W+V+R+U-V,V=W+V+R+U+V+W+V+R-W,W=V+R+U+V+W+V+R-W+V+R+U+V+W-V,R2=FF,U2=F^*F/-*F/^F-F^*F/,V2=*F/^^^F,W2=F^*F/,_a=60,_j=1,_k=1,_l=.5,_m=1.7320508075688772,_n=3,_cb=#000,_o=0,_cd=#fff3',
  "=blurDemoPentagram,S=FX++FX++FX++FX++FX,X=[++++/F/F!X!*F],_a=36,_j=1,_k=1,_l=22,_m=1.6180339887498948,_n=5,_cc=#f004,_cd=#00f7",
  "=TODO,_k=1,_o=0.5,_j=.1,_l=3,_z=2,_cb=#7007,_cc=#0707,_cd=#0077",
  "=KiteDart3,S=Wf+Xf+Wf+Xf+Wf+Xf+Wf+Xf+Wf+X,F=,W=[F][++*F][++f---/f|X-Y|f|W],X=[F+++*F][++/fZ|X|-f|W],Y=[+F][*F][+f/|Y+X],Z=[-F][*F][/f--Wf|+Z],_a=36,_k=4,_l=199,_m=1.6180339887498948,_n=5,_z=9,_hand=1",
  "=Lizard,S=AX,A=[+AX-AX-AX]-AX+AX+AX-,F=,X=F+F+F+FFF-F-F-F,_l=2,_a=60,_n=5",
  /*{
      '': 'AperiodicMirroredMonoTile-Hat',
      S: 'U+V+W+V+R',
      R: 'V+R+U+V+W+V+R-W',
      U: 'V+R+U+V+W+V+R-U+V+W+V+R+U-V',
      V: 'W+V+R+U+V+W+V+R-W',
      W: 'V+R+U+V+W+V+R-W+V+R+U+V+W-V',
      R2: 'FF',
      U2: 'F^*F/-*F/^F-F^*F/',
      V2: '*F/^^^F',
      W2: 'F^*F/',
      _a: 60,
      _l: 5,
      _m: Math.sqrt(3),
      _n: 3
  },*/
  {
    "": "AperiodicMirroredMonoTile-Spectre",
    S: "U+V+W+V+R",
    R: "V+R+U+V+W+V+R-W",
    U: "V+R+U+V+W+V+R-U+V+W+V+R+U-V",
    V: "W+V+R+U+V+W+V+R-W",
    W: "V+R+U+V+W+V+R-W+V+R+U+V+W-V",
    R2: "FF",
    U2: "F^F-F^F-F^F",
    V2: "F^^^F",
    W2: "F^F",
    _a: 60,
    _l: 6,
    _n: 3
  },
  "=Hilbert,S=-!S!F+SFS+F!S!-,_a=90,_l=2,_n=4,_z=1.5",
  "=Penrose,S=X,F=,W=YF++ZF----XF[-YF----WF]++,X=+YF--ZF[---WF--XF]+,Y=-WF++XF[+++YF++ZF]-,Z=--YF++++WF[+ZF++++XF]--XF,_a=36,_l=9,_n=5",
  "=KiteDart1,S=+[/A]F/---[-S]F-F---[-S]*F[/|A],A=[/S]+F/[|A]----F+F----[A]*F,F=f,_a=36,_l=99,_m=1.6180339887498948,_n=5",
  "=KiteDart2,S=[k]++[k]++[k]++[k]++[k],A=[/k]+F/[|A]----F+F----[A]*F,F=f,_a=36,_l=99,_m=1.6180339887498948,k=+[/A]F/---[-k]F-F---[-k]*F[/|A],_n=5",
  "=try90,S=X,F=F+/f*-F,X=[X]F^[X]F^[X]F^[X]F^,_a=80,_l=9,_m=1.4142,_n=5",
  "=tilesg5,S=AX,A=F+F-F,F=,X=[+AX-AX-AX]-AX+AX+AX-,_a=60,_l=6,_n=5",
  "=tilesg6,S=AX,A=FfF,F=,X=[+AX-AX-AX]-AX+AX+AX-,_a=60,_l=6,f=,_n=5",
  "=tilesg7,S=AX,A=++F--f++F--,B=++F--f++F--,C=++F--f++F--,D=++F--f++F--,E=++F--f++F--,F=,G=++F--f++F--,X=[+AX-BX-CX]-DX+EX+GX-,_a=60,_l=6,f=,_n=4",
  "=tilesgHex,S=AX,A=F-F-F-F+F+F+F,F=,X=[+AX-AX-AX]-AX+AX+AX-,_a=60,_l=6,f=,_n=4",
  "=Quartet,S=FB,A=FBFA+HFA+FB-FA,B=FB+FA-FB-JFBFA,F=,H=-,J=+,_a=90,_n=4",
  "=Koch5,S=F-F-F-F,F=F-F+F+FFF-F-F+F,_a=90,_n=3",
  "=QuadKoch,S=F-F-F-F-,F=F+FF-FF-F-F+F+FF-F-F+F+FF+FF-F,_a=90,_n=3",
  "=Koch,S=F--F--F,F=F+F--F+F,_a=60,_l=2,_n=5",
  "=tilesg4,S=X,F=F+f-F,X=[X]F+[X]F+[X]F+[X]F+[X]F+[X]F+,_a=60,_l=6,f=F,_n=5",
  "=lars2,S=+[F]++[F]++[F]++F,F=F[+F][-F],_a=60,_n=6",
  "=Vlinders1,S=f----f----f,_a=30,_l=160,_m=1.732,f=[F]/+f--f+*,_n=7",
  "=Notsupported(*)Vlinders3,S=[--F]f--[--F]f--[--F]f--[--F]f--[--F]f--[--F]f,_a=30,_l=160,_m=1.732,f=/[-(2)F]+f--[--]f[----(2)F]+*,_n=4",
  "=Sierpinski3,S=YF,X=YF+XF+Y,Y=XF-YF-X,_a=60,_n=5",
  "=sierpin,S=--X,F=FF,X=++FXF++FXF++FXF,_a=60,_n=5",
  "=CircularTile,S=X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X+X,X=[F+F+F+F[---X-Y]+++++F++++++++F-F-F-F],Y=[F+F+F+F[---Y]+++++F++++++++F-F-F-F],_a=15,_n=3",
  "S=+FFFFF,_n=1",
  "=ColorTriangGasket,S=--X,F=FF,X=++FXF++FXF++FXF>1,_a=60,_n=4",
  "=curve3,S=F-F-F-F-,F=FF-F+F-F-FF,_a=90,_l=6,_n=4",
  "=curve4,S=F-F-F-F-,F=FF-F-F-F-F-F+F,_a=90,_l=6,_n=4",
  "=Cesaro,S=F^F^F^F^,F=+!F!--!F!+,_a=42,_n=5",
  "=Cesa,S=XY|XY,A=-F++F-,X=XYA^XY|XY,Y=A^XY,_a=30,_l=6,_n=4",
  "=Fass1,S=L,L=LF+RFR+FL-F-LFLFL-FRFR+,R=-LFLF+RFRFR+F+RF-LFL-FR,_a=90,_l=6,_n=4",
  "=fibonacci,S=X,X=F[+X]-FX,_a=90,_l=6,_n=10",
  "=FlowSnake,S=FL,F=,L=FL-FR--FR+FL++FLFL+FR-,R=+FL-FRFR--FR-FL++FL+FR,_a=60,_n=3",
  "=Pentigree,S=F-F-F-F-F,F=F-F++F+F-F-F,_a=72,_n=5",
  "=Lace2,S=w,_a=30,_l=4,w=+++x--F--zFx+,x=---w++F++yFw-,y=+zFx--F--z+++,z=-yFw++F++y---,_n=6",
  "=Island1,S=F+F+F+F,F=FFFF-F+F+F-F[-fFF+F+FF+F]FF,_a=90,_m=6,f=*f/,_n=2",
  "=Island2,S=F+F+F+F,F=F+gF-FF-F-FF+g+FF-gF+FF+F+FF-g-FFF,_a=90,_m=6,g=*f/,_n=3",
  "=ize2,S=XY++XY,X=XYF+XY++XY,Y=F+XY,_a=90,_l=6,_n=5",
  "=ize3,S=F----F----F,F=[-F]+F--F+,_a=30,_l=6,_n=7",
  "=Demon,S=FS+,F=SF-,_a=45,_l=4,_n=12",
  "=Dragon,S=+FX,F=,X=-FX++FY-,Y=+FX--FY+,_a=45,_n=10",
  "=DragonCurve,S=X,X=X-YF-,Y=+FX+Y,_a=90,_n=8",
  "=Dragonka,S=F,F=F+F-F,_a=120,_l=22,_n=8",
  "=Dragonka2,S=/[F+S]|F+S,F=f,_a=30,_l=234,_m=1.4142,_n=10",
  "=XmasColor,S=FU--1FP++++1FQ--,F=,P=--FR++++1FS--1FU,Q=FT++1FR----1FS++,R=++FP----1FQ++1FT,X=P,T=+FU--1FP+,U=-FQ++1FT-,_a=36,_n=7",
  "=Peano1,S=FXY++F++FXY++F,X=XY*-F/-FXY++F++FXY,Y=-*F-/FXY,_a=45,_m=1.41,_n=4",
  "=Peano2,S=X,X=XFYFX+F+YFXFY-F-XFYFX,Y=YFXFY-F-XFYFX+F+YFXFY,_a=90,_n=4",
  "=Pentagram,S=FX++FX++FX++FX++FX,X=[++++/F/F!X!*F],_a=36,_l=222,_m=1.6180339887498948,_n=5",
  "=PentaPlexy,S=F++F++F++F++F,F=F++F++F+++++F-F++F,_a=36,_n=3",
  "=Sierpinski1,S=F-F-F,F=F[-F]F,_a=120,_n=4",
  "=Sierpinski2,S=X,F=FF,X=++FXF++FXF++FXF,_a=60,_n=6",
  "=Sierpinski4,S=F,F=FXF,X=+FXF-FXF-FXF+,_a=120,_n=5",
  "=Sierpinski5,S=FXF--FF--FF,F=FF,X=--FXF++FXF++FXF--,_a=60,_n=3",
  "=sierpinskiSquare1,S=F+F+F+F,F=FF+F+F+F+FF,_a=90,_n=4",
  "=sierpinskiSquare3,S=A,A=AfAfA-f+A-f+A|f|A|f|A+f-AfF-F-F-Ff+f|,F=FFF,_a=90,f=fff,_n=4",
  "=sierpinskiSquare2,S=A,A=AFAFAF-FAFAF-FAFAF-FAFF-,F=fff,_a=90,f=fff,_n=5",
  "=SnowFlake1,S=FR,F=,R=++!FRFU++FU++FU!---*FU|-/!FRFU!,U=!FRFU!|+*FR/+++!FR--FR--FRFU!--,_a=30,_m=1.732,_n=5",
  "=Snowflake2!,S=F,F=++!F!F--F--F/|+F!F--F--F!+++*F/|+F!F*|+F!F,_a=30,_l=60,_m=1.732,_n=4",
  "=SnowFlake3,S=Fx,F=,_a=30,_m=1.732,x=++F!x!Fy--Fx--Fy|+/FyF!x!++F!y!++F!y!Fx*+++F!y!Fx,y=FyF!x!+++/FyF!x!++F!x!++F!y!Fx*|+Fx--Fy--FxF!y!++,_n=4",
  "=Sphinx2,S=+++X,F=ff,X=+FF-YFF+FF--FFF+++X+++F--YFFFYFFF+++,Y=-FF+XFF-FF++FFF+++Y+++F++XFFFXFFF+++,_a=60,_l=6,f=ff,_n=4",
  "=SpiralOrNotTile,S=X++X++X++X++|G|X++X++X++X,X=[FX+++++*F/[-----Y]+++++F],Y=[F+++++*F/[-----Y]+++++F],_a=22.5,_m=0.7653668647,_n=6",
  "=SquareGasket,S=X,F=FF,X=+FXF+FXF+FXF+FXF,_a=90,_n=4",
  "=Peano3,S=F-F-F-F,F=F-F+F+F+F-F-F-F+F,_a=88,_n=3",
  "=Notsupported(*)Vlinders6,S=F-[(0.5)-F]F-[(0.5)-F]F-[(0.5)-F]F-[(0.5)-F]F-[(0.5)-F]F--(0.5)F^/f(2)-S,_a=60,_l=160,_m=1.73205080756887729352744,_n=7",
  "=Vlinders(q3)is*sqrt(3)),S=F-[/-F]F-[/-F]F-[/-F]F-[/-F]F-[/-F]F--/F^(q3)/f*-S,_a=60,_l=160,_m=2,_n=7",
  "=plant04,S=F,F=FF-[-F+F+F]+[+F-F-F],_a=22.5,_n=4",
  "S=f+f-fSF+FSF,_n=4",
  "=hex,S=F,F=-F+F+[+F+F]-,_a=60,_n=5",
  "=strq,S=FS+Sf+fS++SSFf,_n=4",
  "=abc,S=[F+fff+[f,f=F,F=S!Sf+],_n=8,_z=9,_l=3",
  //'=Lace,S=F++F++F++F,F=F+++F---F+F---F++F--F++F,_a=45,_n=3',
  //'=man,S=F++F++F++F,F=-F-FF+++F+FF-F,_a=45,_n=5',
  //'=SnowflakeColor!,S=F,1=1,X=--!F1!F1++F1++F1*|-F1!F1++,F=F1++F1!---/F1*|-F1!F1/|-F1!F1,_a=30,_m=1.732,_n=3',
  //'=ize4,S=F-F-F-F-F-F-F-F-F-F,F=FF+F+F+F+FF,_a=89.8536,_l=6,_n=4',
  //'=ize5,S=A,A=FA+B,B=FA-B,F=FA,_a=45,_l=6,_n=13',
  //'=plant01,S=F,F=F[+F]F[-F]F,_a=25,_l=6,_n=5',
  //'=plant02,S=F,F=F[+F]F[-F][F],_a=20,_l=6,_n=5',
  //'=plant03,S=X,F=FF,X=F[+X][-X]FX,_a=25,_l=6,_n=5',
  //'=plant05,S=X,F=FF,X=F[+X]F[-X]+X,_a=20,_l=6,_n=5',
  //'=plant06,S=X,F=FF,X=F-[[X]+X]+F[+FX]-X,_a=22,_l=6,_n=5',
  //'=plant07,S=F,F=FF-[XY]+[XY],X=+FY,Y=-FX,_a=22,_l=6,_n=5',
  //'=plant08,S=FX,X=*[-FX]+FX,_a=16.3636,_m=0.85,_l=99,_n=6',
  //'=plant09,S=Z,X=X[-FFF][+FFF]FX,Z=ZFX[+Z][-Z],_a=25,_l=6,_n=5',
  //'=plant10,S=A,A=F[+X]FB,B=F[-Y]FA,F=*F/,X=A,Y=B,_a=45,_m=1.3,_n=13',
  //'=plant11,S=A,A=F[+x]Fb,F=*F/,_a=45,_m=1.36,b=F[-y]FA,x=A,y=b,_n=8',
  //'=plant13,S=[+++Z][---Z]TS,H=-Z[+H]L,L=[-FFF][+FFF]F,T=TL,Z=+H[-Z]L,_a=18,_n=6',
  //'=plant12,S=A,A=F[////////+A]F/B,B=F[////////-B]F/A,_a=45,_m=1.1,_n=14',
  //'=Notsupported(*)plant14,S=x,A=c,F=*F/,b=e,c=o,e=h,h=j,j=y,o=p,p=x,x=F[+A(4)]Fy,y=F[-b(4)]Fx,_a=45,_m=1.18,_n=20,_l=1',
  //'=strt,S=FSF--[+FS]++++-[-],_n=8,_a=90',
  //'=Penrose2,S=++ZF----XF-YF----WF,F=,W=YF++ZF----XF[-YF----WF]++,X=+YF--ZF[---WF--XF]+,Y=-WF++XF[+++YF++ZF]-,Z=--YF++++WF[+ZF++++XF]--XF,_a=36,_l=9,_n=4',
  //'=Penrose3,S=[Y]++[Y]++[Y]++[Y]++[Y],F=,W=YF++ZF----XF[-YF----WF]++,X=+YF--ZF[---WF--XF]+,Y=-WF++XF[+++YF++ZF]-,Z=--YF++++WF[+ZF++++XF]--XF,_a=36,_l=9,_n=4',
  //'=Notsupported(*)Vlinders2,S=f----f----f,_a=30,_l=160,_m=1.732,f=[F]/[-(2)F]+f--[--F]f[----(2)F]+*,_n=7',
  //'=Notsupported(*)Vlinders4,S=[--F]f--[--F]f--[--F]f--[--F]f--[--F]f--[--F]f,_a=30,_l=160,_m=1.732,f=/[-(2)F++(0.5)F]+f--[--]f[----(2)F--(0.5)F]+*,_n=4',
  //'=Notsupported(*)Vlinders5,S=AAAAAA,A=[--F]f--,B=-(2)F,_a=30,_l=160,_m=1.732,f=/[B]+f--f[---B]+*,_n=8',
  //'=Fass2,S=L,L=LFLF+RFR+FLFL-FRF-LFL-FR+F+RF-LFL-FRFRFR+,R=-LFLFLF+RFR+FL-F-LF+RFR+FLF+RFRF-LFL-FRFR,_a=90,_l=6,_n=4',
  //'=QuadGosper,S=Fr,F=,L=FLFL-Fr-Fr+FL+FL-Fr-FrFL+Fr+FLFLFr-FL+Fr+FLFL+Fr-FLFr-Fr-FL+FL+FrFr-,_a=90,_l=6,r=+FLFL-Fr-Fr+FL+FLFr+FL-FrFr-FL-Fr+FLFrFr-FL-FrFL+FL+Fr-Fr-FL+FL+FrFr,_n=2',
];
